### ISSUE TITLE
Braille gestures don't seem to work when local system uses BRLTTY

### ISSUE THREAD

**Issue by miguelross** [leonardder/rdAccess#14]
There's a problem with braille we can read braille on braille display but we can't use the command thumb braille key etc to use to be able to move the braille display around the screen.

**Comment by leonardder** [comment]
Could you please provide the following information?

1. What braille display are you using?
2. Are the keys working correctly when operating the local system?
3. Could you please provide a log file of the remote system? Consult [the NVDA wiki](https://github.com/nvaccess/nvda/wiki/LogFilesAndCrashDumps) for details on how to collect a log file.

**Comment by miguelross** [comment]
My braille display is use by brltty it's a powerbraille 40.  The keys work properly in local environment.
her's my log
INFO - __main__ (10:59:25.016) - MainThread (15616):
Starting NVDA version 2023.2
INFO - core.main (10:59:25.485) - MainThread (15616):
Config dir: C:\Users\rosm01\AppData\Roaming\nvda
INFO - config.ConfigManager._loadConfig (10:59:25.485) - MainThread (15616):
Loading config: C:\Users\rosm01\AppData\Roaming\nvda\nvda.ini
INFO - core.main (10:59:26.098) - MainThread (15616):
Windows version: Windows 10 22H2 (10.0.19045) workstation AMD64
INFO - core.main (10:59:26.098) - MainThread (15616):
Using Python version 3.7.9 (tags/v3.7.9:13c94747c7, Aug 17 2020, 18:01:55) [MSC v.1900 32 bit (Intel)]
INFO - core.main (10:59:26.099) - MainThread (15616):
Using comtypes version 1.1.11
INFO - core.main (10:59:26.099) - MainThread (15616):
Using configobj version 5.1.0 with validate version 1.0.1
INFO - synthDriverHandler.setSynth (10:59:26.982) - MainThread (15616):
Loaded synthDriver sapi4
WARNING - mathPres.initialize (10:59:26.999) - MainThread (15616):
MathPlayer 4 not available
INFO - core.main (10:59:27.342) - MainThread (15616):
Using wx version 4.1.1 msw (phoenix) wxWidgets 3.1.5 with six version 1.16.0
INFO - brailleInput.initialize (10:59:27.344) - MainThread (15616):
Braille input initialized
INFO - braille.initialize (10:59:27.344) - MainThread (15616):
Using liblouis version 3.25.0
INFO - braille.initialize (10:59:27.344) - MainThread (15616):
Using pySerial version 3.5
INFO - braille.BrailleHandler._setDisplay (10:59:27.356) - MainThread (15616):
Loaded braille display driver 'noBraille', current display has 0 cells.
INFO - core.main (10:59:27.612) - MainThread (15616):
Java Access Bridge support initialized
INFO - UIAHandler.UIAHandler.MTAThreadFunc (10:59:27.717) - UIAHandler.UIAHandler.MTAThread (15328):
UIAutomation: IUIAutomation6
INFO - braille.BrailleHandler._setDisplay (10:59:28.292) - ThreadPoolExecutor-0_0 (14972):
Loaded braille display driver 'remote', current display has 0 cells.
WARNING - logging.Logger.warn (10:59:28.730) - MainThread (15616):
C:\Users\rosm01\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\Profiles\remote\default\profile.ini inaccessible
WARNING - logging.Logger.warn (10:59:28.732) - MainThread (15616):
No main gestures map (C:\Users\rosm01\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\Profiles\remote\default\gestures.ini; C:\Users\rosm01\AppData\Roaming\nvda\addons\BrailleExtender\globalPlugins\brailleExtender\Profiles\remote\default\gestures.ini) found
INFO - external:globalPlugins.brailleExtender.GlobalPlugin.__init__ (10:59:28.732) - MainThread (15616):
BrailleExtender 23.09.07-ccd0066 loaded (0.09s)
INFO - core.main (10:59:28.736) - MainThread (15616):
NVDA initialized

**Comment by miguelross** [comment]
Ok I try that brailleextender will be desactivate.

**Comment by miguelross** [comment]
You have write ther's a conflict with brailleextender but I need it for my other braille display wich is a focus elbraille 40 that I modify to put JAWS outside and use nvda and for the braille keyboard we need brailleextender to use.

**Comment by leonardder** [comment]
I'm not saying there's a conflict with braille extender, I just want to make sure that there is no conflict. SO if you could test without braille extender, that would be most helpful. We really need to know whether there's a conflict.

**Comment by miguelross** [comment]
That's what I say this is the problem I test it with out brailleextender and the keynavigation work fine.

**Comment by leonardder** [comment]
This is indeed definitely an issue in braille extender, so I'm closing this issue. Please file an issue against braille extender.
@aaclause: for reference. In short, you should consider stopping monkeypatching `inputCore.InputManager.executeGesture` and use the `inputCore.decide_executeGesture` extension point instead`.
