### ISSUE TITLE
Checkbox state changes are sometimes not reported

### ISSUE THREAD

**Issue by cary-rowen** [leonardder/rdAccess#6]
## Steps to reproduce
1. The following operations are completed on the remote server.
2. Select remote speech speech synthesizer;
3. Try changing the state of the options checkbox in NVDA Documentation Settings with a space.
## Expected performance
It should always be possible to consistently report state changes.

**Comment by leonardder** [comment]
Thanks for reporting, I'll have a look over the weekend.

**Comment by cary-rowen** [comment]
Thanks, another thing I found was that NVDA didn't report the list control's current selection when the list control got focus.

## Simple steps to reproduce:
1. NVDA+Ctrl+D Open NVDA Settings panel→Document Format Settings.
2. Press Shift+Tab to give the category list focus.

## actual performance:
NVDA does not reports the currently selected item in the list - document format.

This is a useful add-on that makes the remote desktop experience really nice.

Best

**Comment by cary-rowen** [comment]
Hi,

Is there any progress on this?

Best

**Comment by leonardder** [comment]
I'm sorry, I haven't been able to reproduce this reliably. It is still on my radar, though it probably won't have a fix before NVDA 2023.2 beta is out.

**Comment by cary-rowen** [comment]
I'm also hoping for some logging to help with this.

**Comment by leonardder** [comment]
Could you tell what speech synthesizer you're using on the local system? Does changing the local synth chang anything regarding this issue?

**Comment by cary-rowen** [comment]
Hi @leonardder 
I'm using the WorldVoice speech synthesizer, but I recently upgraded my synthesizer and also to the latest RDAccess The problem doesn't seem to be happening anymore, I'm close it now. I will reopen if necessary later.

**Comment by leonardder** [comment]
Great to hear that it seems more stable now!
